### PR TITLE
LRQA-67927 Remove test from quarantine

### PR DESCRIPTION
**Pull request by naraandrade**

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by lucasperj** [comment]
Just started reviewing :)

**Comment by lucasperj** [comment]
Test needed to go through a refactor, I assumed, [changed branches](https://github.com/lucasperj/liferay-portal/pull/21) and sent. Thanks!

**Comment by lucasperj** [comment]
Test needed to go through a refactor, I assumed, [changed branches](https://github.com/lucasperj/liferay-portal/pull/21) and sent. Thanks! You can close that PR.

**Pull request closed without merging**
