### PR TITLE
LRQA-70026 Update row position of Knowledge Base Article and remove test from quarantine

### PR DESCRIPTION
**Pull request by naraandrade**

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:workflow

**Comment by lucasperj** [comment]
ci:stop

**Comment by lucasperj** [comment]
ci:stop

**Comment by lucasperj** [comment]
ci:stop

**Comment by lucasperj** [comment]
ci:forward

**Pull request closed without merging**
