### PR TITLE
LPS-183584 Use MarketPlace app category and tag instead of MarketPlace Solutions

### PR DESCRIPTION
**Pull request by igor-franca**
Related [Ticket](https://issues.liferay.com/browse/LPS-183584)

### CODE REVIEW

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
To test this PR you should go to global site, categorization and create 'Marketplace App Category'
and 'Marketplace App Tags'.

Add some categories and go to publisher dashboard, add app and see the new categories and tags.

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/134405

**Pull request closed without merging**
