### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by albinojunior**

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:test:workflow

**Comment by naraandrade** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by naraandrade** [comment]
Pull request submitted to https://github.com/gabrielpramos/liferay-portal/pull/58. [See changes here.](https://github.com/naraandrade/liferay-portal/compare/6241b698fe9d~13...6241b698fe9d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
