### PR TITLE
LPS-178343 Create buttons and forms of Payment methods on Modal

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
Hi Nara, I made a push force now just to fix an issue on deploy I didn't notice yesterday.
It was just add this restriction here: `selectedPaymentMethod={selectedPaymentMethod as string}`

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/133413

**Pull request closed without merging**
