### PR TITLE
LRQA-66240 Always call AssertElementNotPresent

### PR DESCRIPTION
**Pull request by naraandrade**

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:workflow

**Comment by naraandrade** [comment]
ci:test:calendar

**Comment by naraandrade** [comment]
ci:stop

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:workflow

**Comment by naraandrade** [comment]
ci:test:calendar

**Comment by lucasperj** [comment]
ci:forward

**Comment by lucasperj** [comment]
ci:forward

**Pull request closed without merging**
