### PR TITLE
LPS-180663

### PR DESCRIPTION
**Pull request by igor-franca**
[Related Ticket](https://issues.liferay.com/browse/LPS-180663)

### CODE REVIEW

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — CHANGES_REQUESTED** [review]
@igor-franca Please, call the gate for the publisher dashboard instead of customer dashboard. Also, if the user is not logged in they should be redirected to the gate as well.

**Comment by igor-franca** [comment]
> @igor-franca Please, call the gate for the publisher dashboard instead of customer dashboard. Also, if the user is not logged in they should be redirected to the gate as well.

Done 👍🏾

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/133242

**Pull request closed without merging**
