### PR TITLE
LRQA-69907 Create new macro to expand the Resources Availability panel

### PR DESCRIPTION
**Pull request by naraandrade**

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:calendar

**Comment by naraandrade** [comment]
ci:test:workflow

**Comment by lucasperj** [comment]
ci:forward

**Comment by lucasperj** [comment]
ci:forward

**Pull request closed without merging**
