### PR TITLE
LPS-181981_v2  Create Account Selector

### PR DESCRIPTION
**Pull request by alinedoleron**
Ticket: https://issues.liferay.com/browse/LPS-181981

It fixes the following bugs:

LPS Ticket | Issue Description
-- |  --
LPS-182572 | Free App with 0 price opens with Paid-app UI
LPS-182573 | Paid app doesn't validate billing address fields
--  | Paypal logo doesnt appear on checkout
LPS-182574 | App crashes on LXC with 404 when app doesnt have Address, on checkout. Get-app disappears.

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:sf

**Review by danvb112 — CHANGES_REQUESTED** [review]
hey @alinedoleron  good work on this Story! I have some suggestions, feel free to ask me anyhing :smile:

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/134009

**Comment by alinedoleron** [comment]
https://github.com/naraandrade/liferay-portal/pull/213

**Pull request closed without merging**
