### PR TITLE
LPS-109713 Regen

### PR DESCRIPTION
**Pull request by albinojunior**

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:test:workflow

**Comment by naraandrade** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by naraandrade** [comment]
Pull request submitted to https://github.com/inacionery/liferay-portal/pull/454. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
